[tool.pylint.MASTER]
ignore-paths = ["template/*.py"]

[tool.pylint."MESSAGES CONTROL"]
disable = ["missing-function-docstring", "missing-module-docstring"]

[tool.pytest.ini_options]
python_files = "**/part*.py"
addopts = "--ignore=template"

[tool.pyright]
include = ["day*"]